version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
